#' Extract Bayes Empiracle Bayes information from codeml output
#'
#' Extracts all sites reported in the Bayes Empiracle Bayes section of the codeml output as a dataframe object
#' @param dir_path Directory path to codeml_parallel output directory
#' @param out_path Directory of where to write data frame object generated by parse_BEB()
#' @param cores Number of cores to multi-thread over
#' @param ext Extension of CODEML output files
#' @keywords Bayes, empiracle, Bayes, parse
#' @export
#' @examples
#' getBEB(dir_path = "path/to/parent_out", models = c("M2a", "M8", "ModelA"), cores = 4, ext = ".customOut")
getBEB <- function(dir_path, models, cores = 1, ext = ".out") {

  ## Models with BEB output
  m <- c("M2a", "M8", "ModelA")

  ## Check model inputs
  if (!all(models %in% m)) {
    print(paste("Accepted models:", m, sep = " "))
    print(paste("Your models:", models, sep = " "))
    stop("One of the models above does not contain BEB values")
  }

  ## Importing all log files
  d <- list.dirs(path = dir_path, full.names = TRUE)
  d <- d[stringr::str_detect(string = d, pattern = paste(models, "$", sep = "", collapse = "|"))]

  ## Setting names of dirs vector
  n <- sub(".*/", "", d)
  d <- magrittr::set_names(x = d, value = n)

  ## Importing data
  print("Reading output files")
  f <- purrr::map(d, ~{
    fl <- list.files(path = .x, pattern = ext, full.names = TRUE)
    fl <- magrittr::set_names(x = fl, value = sub(ext, "", basename(fl)))
    purrr::map(fl, readr::read_lines)
  })

  ## Parsing BEB from models
  beb <- purrr::map(.x = names(f), ~{

    # print(paste("Parsing BEB from:", .x, sep = " "))
    if (.x == "M2a" | .x == "M8") {

      .parse_m2a_M8(lines = f[[.x]], c = cores)

    } else if (.x == "ModelA") {

      .parse_ModelA(lines = f[[.x]], c = cores)

    }

  })

  ## Single tibble
  beb <- magrittr::set_names(x = beb, value = names(f))
  beb <- dplyr::bind_rows(beb, .id = "model")
  beb <- tidyr::separate(data = beb, col = id, into = c("gene", "tree"), sep = "_")
  beb <- dplyr::mutate(.data = beb, tree = stringr::str_replace_na(string = tree, replacement = "base"))

  print("Getting no-gap-length value")
  alnLength <- purrr::map(f[[1]], ~{

    r <- head(x = .x, n = 3)
    r <- trimws(x = r)
    r <- r[stringr::str_detect(string = r, pattern = "^3")]
    r <- stringr::str_split(string = r, pattern = "\\s+")
    r <- unlist(x = r)
    tibble::tibble(no_gap_length = as.numeric(r[[2]]))

  })

  alnLength <- dplyr::bind_rows(alnLength, .id = "gene")
  alnLength <- dplyr::mutate(.data = alnLength, condition = sub("_.*", "", gene))
  # alnLength <- tidyr::separate(data = alnLength, col = condition, into = c("gene", "tree"), sep = "_")

  beb <- dplyr::left_join(beb, alnLength)

  # ## Return a list object of long form and nested
  lst <- split(x = beb, beb[["model"]])
  nst <- dplyr::group_by(.data = beb, model)
  nst <- tidyr::nest(data = nst, .key = "BEB")

  o <- list(long = beb, list = lst, nested = nst)

  return(o)
}
