#' Extract Bayes Empiracle Bayes information from codeml output
#'
#' Extracts all sites reported in the Bayes Empiracle Bayes section of the codeml output as a dataframe object
#' @param dir_path Directory path to codeml_parallel output directory
#' @param out_path Directory of where to write data frame object generated by parse_BEB()
#' @keywords Bayes, empiracle, Bayes, parse
#' @export
#' @examples
#' parse_BEB(dir_path = "path/to/parent_out, out_path = "path/to/output/name.tsv")
parse_BEB <- function(dir_path, out_path = NULL) {

  ## Importing data
  fl <- list.files(path = dir_path, pattern = "Model2Selection_", full.names = TRUE, recursive = TRUE)
  fl <- set_names(x = fl, value = basename(str_remove(string = fl, pattern = ".output")))
  lst.fl <- map(fl, read_lines)

  ## Iterating through each file extracting Bayes Empirical Bayes values
  lst.beb <- map(lst.fl, ~{

    int.start <- grep(pattern = "Bayes Empirical Bayes", x = .x)
    int.end <- grep(pattern = "The grid \\(see ternary graph for p0-p1\\)", x = .x)

    ## Conditional to get the right output
    if (isTRUE(.x[(int.start + 2)] == "") | is_empty(.x[(int.start + 2)])) {

      vec.sub <- c("NA NA NA") ## Entry for samples that don't have any information

    } else {

      vec.sub <- .x[(int.start+2):(int.end-3)]
      vec.sub <- trimws(x = vec.sub)

    }

  })

  lst.alignLength <- map(lst.fl, ~{
    int.noGapLen <- .x[grep(pattern = "After deleting gaps.", .x)]
    int.noGapLen <- as.numeric(sub(".*\\.\\s+(.*)\\s+sites", "\\1", int.noGapLen))
    tibble(no_gap_length = int.noGapLen)
  }) %>%
    bind_rows(.id = "condition") %>%
    mutate(condition = gsub("Model2Selection_", "", condition))

  ## Removing NULL elements
  lst.beb <- lst.beb[!sapply(lst.beb, is.null)]

  ## Converting to long-format dataframe
  df.beb <- map(lst.beb, ~{
    .x %>%
      enframe(name = NULL) %>%
      separate(col = value, into = c("aa_position", "aa", "val"), sep = " ")
  }) %>%
    bind_rows(.id = "condition") %>%
    mutate(condition = str_remove(string = condition, pattern = "Model2Selection_"),
           pval = val) %>%
    mutate(pval = 1 - as.numeric(str_remove_all(string = pval, pattern = "\\*")),
           signif = str_extract(string = val, pattern = "\\*+"),
           val = str_remove(val, "\\*+"),
           val = as.numeric(val),
           aa_position = as.integer(aa_position))

  df.beb <- left_join(df.beb, lst.alignLength) %>%
    separate(col = condition, into = c("gene", "tree"), sep = "_")

  ## Write outputs
  if (!is.null(out_path)) {

    write_tsv(x = df.beb, path = out_path, col_names = TRUE)

  }

  return(df.beb)

}
